name: Jira API Manual Trigger

on:
  workflow_dispatch:

jobs:
  build-and-call:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build binary
        run: go build -o jira-caller main.go

      - name: Run Jira API binary
        run: |
          echo "▶️ Rodando binário para criar issue no Jira..."
          ./jira-caller
        env:
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
